using System;
using System.Windows;
using System.Windows.Controls;

namespace DistanceLearningSystem.Views.Pages.Admin
{
    public partial class DataBaseDataGrid : Page
    {
        public DataBaseDataGrid()
        {
            InitializeComponent();
        }

        private void DataGrid_OnAutoGeneratedColumns(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            switch (e.PropertyName)
            {
                case "Id":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Gender":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Name":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "SurName":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Patronymic":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Role":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "FullName":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Year":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "FacultyId":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "Number":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "SpecialityId":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                case "NumberOfCourses":
                    e.Column.Visibility = Visibility.Visible;
                    break;
                default:
                    e.Column.Visibility = Visibility.Collapsed;
                    break;
            }
        }
    }
}