DELETE
FROM USER_LOGINS;
DELETE
FROM USER_PROFILES;

INSERT INTO USER_LOGINS(USER_LOGIN, USER_PASSWORD,USER_ROLE)
VALUES ('admin', '$2a$10$YK4GLW1dgefLQV6Wg1/lReNLZvjLWabLKdHSN7aLPmMxa3jdT61kS','admin');
INSERT INTO USER_LOGINS(USER_LOGIN, USER_PASSWORD,USER_ROLE)
VALUES ('kek', 'qwerty','user');
