CREATE TABLE TRAIN_TYPES
(
    TRAIN_TYPE_ID   RAW(16) DEFAULT SYS_GUID() NOT NULL,
    TRAIN_TYPE      VARCHAR2(150)              NOT NULL UNIQUE,
    TRAIN_TYPE_COST NUMBER(4, 2)               NOT NULL,
    CONSTRAINT TRAIN_TYPES_PK PRIMARY KEY (TRAIN_TYPE_ID)
);
drop table TRAIN_TYPES;

CREATE TABLE TRAINS
(
    TRAIN_ID      RAW(16) DEFAULT SYS_GUID() NOT NULL,
    TRAIN_NAME    VARCHAR2(50)               NOT NULL UNIQUE,
    TRAIN_TYPE_ID RAW(16)                    NOT NULL,
    CONSTRAINT TRAINS_PK PRIMARY KEY (TRAIN_ID),
    CONSTRAINT TRAINS_TRAIN_TYPE_FK FOREIGN KEY (TRAIN_TYPE_ID) REFERENCES TRAIN_TYPES (TRAIN_TYPE_ID)
);
drop table TRAINS;
CREATE TABLE WAGGONS_TYPES
(
    TYPE_ID          RAW(16) DEFAULT SYS_GUID() NOT NULL,
    WAGGON_TYPE_NAME VARCHAR2(150)              NOT NULL UNIQUE,
    WAGGON_TYPE_SIZE NUMBER(4)                  NOT NULL,
    WAGGON_TYPE_COST NUMBER(4, 2)               NOT NULL,
    CONSTRAINT WAGGONS_TYPES_PK PRIMARY KEY (TYPE_ID)
);
drop table WAGGONS_TYPES;

CREATE TABLE WAGGONS
(
    WAGGON_ID      RAW(16) DEFAULT SYS_GUID() NOT NULL,
    WAGGON_NAME    NUMBER(4)                  NOT NULL,
    WAGGON_TYPE_ID RAW(16)                    NOT NULL,
    TRAIN_ID       RAW(16)                    NOT NULL,
    CONSTRAINT WAGGONS_PK PRIMARY KEY (WAGGON_ID),
    CONSTRAINT WAGGONS_WAGGONS_TYPES_FK FOREIGN KEY (WAGGON_TYPE_ID) REFERENCES WAGGONS_TYPES (TYPE_ID),
    CONSTRAINT TRAINS_FK FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS (TRAIN_ID)
);
ALTER TABLE WAGGONS
    DROP COLUMN WAGGON_NAME;
ALTER TABLE WAGGONS
    ADD WAGGON_NAME NUMBER(4) NOT NULL;
drop table WAGGONS;

CREATE TABLE SEATS
(
    SEAT_ID     RAW(16) DEFAULT SYS_GUID()     NOT NULL,
    SEAT_NUMBER NUMBER(2)                      NOT NULL,
    WAGON_ID    RAW(16)                        NOT NULL,
    IS_BOUGHT   CHAR(1) DEFAULT '0'
        CHECK ( IS_BOUGHT IN ('0', '1', '2') ) NOT NULL,
    CONSTRAINT SEATS_PK PRIMARY KEY (SEAT_ID),
    CONSTRAINT SEATS_WAGGONS_FK FOREIGN KEY (WAGON_ID) REFERENCES WAGGONS (WAGGON_ID)
);
drop table SEATS;

CREATE TABLE TICKETS
(
    TICKET_ID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    SEAT_ID   RAW(16)                    NOT NULL,
    CONSTRAINT TICKETS_PK PRIMARY KEY (TICKET_ID),
    CONSTRAINT TICKETS_SEATS_FK FOREIGN KEY (SEAT_ID) REFERENCES SEATS (SEAT_ID)
);
DROP TABLE TICKETS;

CREATE TABLE MOVEMENT_ROUTES
(
    ROUTE_ID   RAW(16) DEFAULT SYS_GUID() NOT NULL,
    ROUTE_NAME VARCHAR2(200)              NOT NULL UNIQUE,
    CONSTRAINT MOVEMENT_ROUTES_PK PRIMARY KEY (ROUTE_ID)
);
DROP TABLE MOVEMENT_ROUTES;

CREATE TABLE MOVEMENT_ROUTES_TRAINS
(
    MOVEMENT_ROUTE_ID RAW(16),
    TRAIN_ID          RAW(16),
    CONSTRAINT MOVEMENT_ROUTES_TRAINS_TRAINS_FK FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS (TRAIN_ID),
    CONSTRAINT MOVEMENT_ROUTES_TRAINS_MOVEMENT_ROUTES_FK FOREIGN KEY (MOVEMENT_ROUTE_ID) REFERENCES MOVEMENT_ROUTES (ROUTE_ID) on delete cascade
);
alter table MOVEMENT_ROUTES_TRAINS
    drop constraint MOVEMENT_ROUTES_TRAINS_TRAINS_FK;
alter table MOVEMENT_ROUTES_TRAINS add constraint MOVEMENT_ROUTES_TRAINS_TRAINS_FK foreign key (TRAIN_ID) references TRAINS (TRAIN_ID) ;
DROP TABLE MOVEMENT_ROUTES_TRAINS;

CREATE TABLE STATIONS
(
    STATION_ID   RAW(16) DEFAULT SYS_GUID() NOT NULL,
    STATION_NAME VARCHAR2(150)              NOT NULL UNIQUE,
    CONSTRAINT STATIONS_PK PRIMARY KEY (STATION_ID)
);

DROP TABLE STATIONS;

CREATE TABLE MOVEMENT_ROUTES_STATIONS
(
    MOVEMENT_ROUTE_ID RAW(16),
    STATION_ID        RAW(16),
    POSITION_NUMBER   NUMBER(5) NOT NULL,
    POSITION_TIME     DATE      NOT NULL,
    CONSTRAINT MOVEMENT_ROUTES_STATIONS_MOVEMENT_ROUTES_FK FOREIGN KEY (MOVEMENT_ROUTE_ID) REFERENCES MOVEMENT_ROUTES (ROUTE_ID) on delete cascade,
    CONSTRAINT MOVEMENT_ROUTES_STATIONS_STATIONS_FK FOREIGN KEY (STATION_ID) REFERENCES STATIONS (STATION_ID)
);
DROP TABLE MOVEMENT_ROUTES_STATIONS;
-----------------------------------------------------------
CREATE TABLE USER_LOGINS
(
    USER_ID       RAW(16) DEFAULT SYS_GUID() NOT NULL,
    USER_LOGIN    VARCHAR2(150)              NOT NULL,
    USER_PASSWORD VARCHAR2(130)              NOT NULL,
    USER_ROLE     VARCHAR2(50)               NOT NULL,
    CONSTRAINT USER_LOGINS_PK PRIMARY KEY (USER_ID)
);
DROP TABLE USER_LOGINS;

CREATE TABLE USER_PROFILES
(
    USER_PROFILE_ID RAW(16)      NOT NULL,
    USER_NAME       VARCHAR2(50) NOT NULL,
    USER_SURNAME    VARCHAR2(50) NOT NULL,
    USER_PATRONYMIC VARCHAR2(50) NOT NULL,
    USER_EMAIL      VARCHAR2(50) NOT NULL UNIQUE,
    USER_PASSPORT   VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT USER_PROFILES_PK PRIMARY KEY (USER_PROFILE_ID),
    CONSTRAINT USER_PROFILES_USER_LOGINS_FK FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_LOGINS (USER_ID)
);
DROP TABLE USER_PROFILES;
CREATE TABLE ORDERS
(
    ORDERS_ID       RAW(16) DEFAULT SYS_GUID() NOT NULL,
    USER_PROFILE_ID RAW(16)                    NOT NULL,
    PRICE           NUMBER(4, 2)               NOT NULL,
    STATION_FROM    VARCHAR2(160)              NOT NULL,
    STATION_TO      VARCHAR2(160)              NOT NULL,
    TIME_FROM       DATE                       NOT NULL,
    TIME_TO         DATE                       NOT NULL,
    CONSTRAINT ORDERS_PK PRIMARY KEY (ORDERS_ID),
    CONSTRAINT ORDERS_USER_PROFILES_FK FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILES (USER_PROFILE_ID) on delete cascade
);
DROP TABLE ORDERS;

CREATE TABLE TICKETS_ORDERS
(
    ORDER_ID  RAW(16) NOT NULL,
    TICKET_ID RAW(16) NOT NULL,
    CONSTRAINT TICKETS_ORDERS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
    CONSTRAINT TICKETS_ORDERS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDERS_ID) on delete cascade
);
DROP TABLE TICKETS_ORDERS;

--FOR send standby
ALTER
    SYSTEM CHECKPOINT;
ALTER
    SYSTEM SWITCH LOGFILE;
ALTER
    SYSTEM archIVE LOG CURRENT;

insert into USER_LOGINS (USER_LOGIN, USER_PASSWORD, USER_ROLE)
values ('admin', '$2a$10$YK4GLW1dgefLQV6Wg1/lReNLZvjLWabLKdHSN7aLPmMxa3jdT61kS', 'ROLE_ADMIN');

insert into USER_PROFILES (USER_PROFILE_ID, USER_NAME, USER_SURNAME, USER_PATRONYMIC, USER_EMAIL, USER_PASSPORT)
values ('4E7238056C0A4E0CB5FA12D7D55C6415', 'admin', 'admin', 'admin', 'admin', 'admin');

